name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-and-push:
    name: Build and Push
    runs-on: codebuild-test-project-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push container
        run: echo "hello"
        
