name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build and push container
        run: echo "Building and pushing..."
    outputs:
      build_output: some_value # optional outputs if needed

  _release-info:
    name: Release Info (Optional)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ github.event.client_payload.releaseData != null || true }} # run if there is release data, otherwise skip
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Generate release info
        run: echo "Release info step..."
    outputs:
      release_data: some_value # optional outputs

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-push # only require build-and-push
    if: ${{ needs['build-and-push'].result == 'success' }}
    steps:
      - name: "Check if _release-info ran"
        run: |
          if [ -n "${{ needs._release-info }}" ]; then
            echo "_release-info ran, can use outputs if needed"
          else
            echo "_release-info skipped, continuing anyway"

      - name: Deploy application
        run: echo "Deploying app..."
