name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and push container
        run: echo "Building and pushing..."

  _release-info:
    name: Release Info (Optional)
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ github.event.client_payload.releaseData != null }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate release info
        run: echo "Generating release info..."
    outputs:
      release_data: "some_value"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build-and-push
      - _release-info
    if: ${{ needs['build-and-push'].result == 'success' && (needs.releaseinfo.result == 'success' || needs.releaseinfo.result == 'skipped') }}
    steps:
      - name: Check if _release-info ran
        run: |
          # safely check optional job
          RELEASE_DATA="${{ needs._release-info.outputs.release_data || '' }}"
          if [[ -n "$RELEASE_DATA" ]]; then
            echo "_release-info ran, can use outputs"
          else
            echo "_release-info skipped, continue anyway"

      - name: Deploy application
        run: echo "Deploying app..."
